// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using proyef.Contexts;

#nullable disable

namespace proyef.Migrations
{
    [DbContext(typeof(TareasContext))]
    [Migration("20220906004848_InitialData")]
    partial class InitialData
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("proyef.Models.Categoria", b =>
                {
                    b.Property<Guid>("CategoriaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Descripcion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<int>("Peso")
                        .HasColumnType("int");

                    b.HasKey("CategoriaId");

                    b.ToTable("Categoria", (string)null);

                    b.HasData(
                        new
                        {
                            CategoriaId = new Guid("20c1bb98-23fc-43b1-8c31-a62083ec0d8b"),
                            Nombre = "hola",
                            Peso = 20
                        },
                        new
                        {
                            CategoriaId = new Guid("f36b02e7-0654-4797-812a-73d2ecc3ae6c"),
                            Nombre = "Personales",
                            Peso = 50
                        });
                });

            modelBuilder.Entity("proyef.Models.Tarea", b =>
                {
                    b.Property<Guid>("TareaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CategoriaId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Descripcion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<int>("PrioridadTarea")
                        .HasColumnType("int");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("TareaId");

                    b.HasIndex("CategoriaId");

                    b.ToTable("Tarea", (string)null);

                    b.HasData(
                        new
                        {
                            TareaId = new Guid("8b0bc293-e80d-43b5-b7f9-553c76e57de4"),
                            CategoriaId = new Guid("20c1bb98-23fc-43b1-8c31-a62083ec0d8b"),
                            FechaCreacion = new DateTime(2022, 9, 5, 19, 48, 48, 18, DateTimeKind.Local).AddTicks(6786),
                            PrioridadTarea = 1,
                            Titulo = "resisar algo"
                        },
                        new
                        {
                            TareaId = new Guid("ff97f1d1-0a63-458a-a96b-3d92f1eef40c"),
                            CategoriaId = new Guid("f36b02e7-0654-4797-812a-73d2ecc3ae6c"),
                            FechaCreacion = new DateTime(2022, 9, 5, 19, 48, 48, 18, DateTimeKind.Local).AddTicks(6800),
                            PrioridadTarea = 0,
                            Titulo = "terminar algo"
                        });
                });

            modelBuilder.Entity("proyef.Models.Tarea", b =>
                {
                    b.HasOne("proyef.Models.Categoria", "Categoria")
                        .WithMany("Tareas")
                        .HasForeignKey("CategoriaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Categoria");
                });

            modelBuilder.Entity("proyef.Models.Categoria", b =>
                {
                    b.Navigation("Tareas");
                });
#pragma warning restore 612, 618
        }
    }
}
